# Generated by Django 2.2.1 on 2019-05-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_file', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='delete_date',
            new_name='finish_date',
        ),
    ]
