# Generated by Django 2.2.1 on 2019-05-22 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('temp_file', '0002_auto_20190520_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='finish_date',
            field=models.DateTimeField(verbose_name='Введите время действия файла'),
        ),
    ]
