# Generated by Django 2.2.1 on 2019-05-23 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp_file', '0005_auto_20190524_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
